import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppText as Text } from '@/components/AppText';
import { events } from '@/data/events';
import { getChecklistItems, getChecklistProgress } from '@/data/checklists';
import { Theme } from '@/constants/theme';

type Tab = 'overview' | 'checklist' | 'guests' | 'vendors';

export default function EventOverviewScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const event = events.find((item) => item.id === id) ?? events[0];
  const [progress, setProgress] = useState(getChecklistProgress(event.id));
  const [pending, setPending] = useState(getChecklistItems(event.id).filter((item) => !item.done).length);
  useFocusEffect(useCallback(() => { setProgress(getChecklistProgress(event.id)); setPending(getChecklistItems(event.id).filter((item) => !item.done).length); }, [event.id, setPending, setProgress]));
  const menu = () => Alert.alert('จัดการงาน', undefined, [{ text: 'แก้ไขงาน', onPress: () => router.push('/event/new') }, { text: 'ทำเครื่องหมายว่าเสร็จแล้ว' }, { text: 'ลบงาน', style: 'destructive' }, { text: 'ยกเลิก', style: 'cancel' }]);
  const openTab = (tab: Tab) => { if (tab === 'checklist') return router.push({ pathname: '/event/checklist', params: { eventId: event.id } }); if (tab === 'guests') return router.push({ pathname: '/event/guests', params: { eventId: event.id } }); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ งานของฉัน</Text></Pressable><Pressable accessibilityLabel="เมนูงาน" onPress={menu}><Text style={styles.more}>•••</Text></Pressable></View><View style={[styles.hero, { backgroundColor: event.banner }]}><Text style={styles.heroIcon}>{event.icon}</Text><Text style={[styles.days, { color: event.accent }]}>{event.status === 'completed' ? 'เสร็จแล้ว' : `อีก ${event.daysLeft} วัน`}</Text></View><Text style={styles.title}>{event.title}</Text><Text style={styles.meta}>{event.date} · {event.venue}</Text><View style={styles.tabs}>{(['overview', 'checklist', 'guests', 'vendors'] as Tab[]).map((tab) => <Pressable key={tab} onPress={() => openTab(tab)} style={[styles.tab, tab === 'overview' && styles.tabActive]}><Text style={[styles.tabText, tab === 'overview' && styles.tabTextActive]}>{tab === 'overview' ? 'ภาพรวม' : tab === 'checklist' ? 'เช็คลิสต์' : tab === 'guests' ? 'แขก' : 'ผู้ขาย'}</Text></Pressable>)}</View><Overview event={event} progress={progress} pending={pending} /></ScrollView></SafeAreaView>;
}

function Overview({ event, progress, pending }: { event: (typeof events)[number]; progress: number; pending: number }) { return <View style={styles.sectionGap}><View style={styles.progressCard}><View style={styles.row}><Text style={styles.cardTitle}>ความคืบหน้าของงาน</Text><Text style={styles.percent}>{progress}%</Text></View><View style={styles.track}><View style={[styles.progress, { width: `${progress}%`, backgroundColor: event.accent }]} /></View></View><View style={styles.stats}><Stat icon="📍" label="สถานที่" value={event.venue} /><Stat icon="💰" label="งบประมาณ" value={`฿${event.budget.toLocaleString()}`} /><Stat icon="👥" label="แขก" value={`${event.guests} คน`} /><Stat icon="⏳" label="งานค้าง" value={`${pending} รายการ`} /></View><Text style={styles.sectionTitle}>งานใกล้กำหนด</Text><Task icon="🛠️" title="ยืนยันรายละเอียดกับผู้ขาย" meta="กำหนดภายใน 3 วัน" /><Task icon="📋" title="ตรวจสอบเช็คลิสต์ที่ยังค้าง" meta={`มี ${pending} รายการรอดำเนินการ`} /></View>; }
function Stat({ icon, label, value }: { icon: string; label: string; value: string }) { return <View style={styles.stat}><Text style={styles.statIcon}>{icon}</Text><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue} numberOfLines={1}>{value}</Text></View>; }
function Task({ icon, title, meta }: { icon: string; title: string; meta: string }) { return <View style={styles.task}><Text style={styles.taskIcon}>{icon}</Text><View style={{ flex: 1 }}><Text style={styles.taskTitle}>{title}</Text><Text style={styles.taskMeta}>{meta}</Text></View><Text style={styles.chevron}>›</Text></View>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Theme.colors.background }, content: { padding: 20, paddingBottom: 40, gap: 12 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 40 }, back: { color: Theme.colors.primary, fontSize: 14, fontWeight: '600' }, more: { color: Theme.colors.text, fontSize: 18, letterSpacing: 2 }, hero: { minHeight: 126, borderRadius: 22, alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 4 }, heroIcon: { fontSize: 42 }, days: { fontSize: 14, fontWeight: '700' }, title: { color: Theme.colors.text, fontSize: 24, fontWeight: '800', marginTop: 4 }, meta: { color: Theme.colors.muted, fontSize: 13 }, tabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: Theme.colors.border, marginTop: 8 }, tab: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center' }, tabActive: { borderBottomWidth: 3, borderBottomColor: Theme.colors.primary }, tabText: { color: Theme.colors.muted, fontSize: 12 }, tabTextActive: { color: Theme.colors.primary, fontWeight: '700' }, sectionGap: { gap: 12 }, progressCard: { backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 18, padding: 16, gap: 12 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, cardTitle: { color: Theme.colors.text, fontSize: 14, fontWeight: '700' }, percent: { color: Theme.colors.primary, fontSize: 14, fontWeight: '700' }, track: { height: 8, backgroundColor: Theme.colors.border, borderRadius: 100, overflow: 'hidden' }, progress: { height: '100%', borderRadius: 100 }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, stat: { width: '48%', backgroundColor: Theme.colors.surface, borderRadius: 16, padding: 12, gap: 4 }, statIcon: { fontSize: 18 }, statLabel: { color: Theme.colors.muted, fontSize: 11 }, statValue: { color: Theme.colors.text, fontSize: 13, fontWeight: '700' }, sectionTitle: { color: Theme.colors.text, fontSize: 16, fontWeight: '700', marginTop: 8 }, task: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 16, padding: 14 }, taskIcon: { fontSize: 20 }, taskTitle: { color: Theme.colors.text, fontSize: 13, fontWeight: '600' }, taskMeta: { color: Theme.colors.muted, fontSize: 11, marginTop: 3 }, chevron: { color: Theme.colors.muted, fontSize: 25 } });
