import { useFocusEffect } from '@react-navigation/native';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BudgetCategory, getBudgetCategory } from '@/data/eventBudget';
import { Theme } from '@/constants/theme';

const money = (value: number) => `฿${value.toLocaleString('en-US')}`;
export default function BudgetCategoryScreen() {
  const { eventId = '', categoryId = '' } = useLocalSearchParams<{ eventId?: string; categoryId?: string }>();
  const [category, setCategory] = useState<BudgetCategory | undefined>(() => getBudgetCategory(eventId, categoryId));
  useFocusEffect(useCallback(() => setCategory(getBudgetCategory(eventId, categoryId)), [eventId, categoryId]));
  if (!category) return <SafeAreaView style={styles.safe}><Text style={styles.empty}>ไม่พบหมวดงบประมาณ</Text></SafeAreaView>;
  const used = category.expenses.reduce((sum, expense) => sum + expense.amount, 0);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ รายละเอียดงบประมาณ</Text></Pressable><Text style={styles.title}>{category.name}</Text><View style={styles.summary}><View><Text style={styles.label}>ใช้แล้ว</Text><Text style={styles.amount}>{money(used)}</Text></View><View><Text style={styles.label}>งบที่ตั้งไว้</Text><Text style={styles.amount}>{money(category.planned)}</Text></View><Text style={styles.percent}>{category.planned ? Math.round((used / category.planned) * 100) : 0}%</Text></View><Text style={styles.section}>รายการย่อย</Text>{category.expenses.length ? category.expenses.map((expense) => <Pressable key={expense.id} onPress={() => !expense.id.startsWith('checklist-') && router.push({ pathname: '/event/budget-expense-new', params: { eventId, categoryId, expenseId: expense.id } })} style={styles.expense}><View style={styles.expenseText}><Text style={styles.name}>{expense.name}</Text><Text style={styles.amountSmall}>{money(expense.amount)}</Text></View><Text style={[styles.status, expense.paid ? styles.paid : styles.unpaid]}>{expense.paid ? 'จ่ายแล้ว' : 'ยังไม่จ่าย'}</Text></Pressable>) : <Text style={styles.empty}>ยังไม่มีรายการย่อยในหมวดนี้</Text>}<Pressable onPress={() => router.push({ pathname: '/event/budget-expense-new', params: { eventId, categoryId } })} style={styles.add}><Text style={styles.addText}>＋ เพิ่มค่าใช้จ่าย</Text></Pressable></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Theme.colors.background }, content: { padding: 20, paddingBottom: 40, gap: 14 }, back: { color: Theme.colors.primary, fontSize: 14, fontWeight: '600', minHeight: 36 }, title: { color: Theme.colors.text, fontSize: 25, fontWeight: '800' }, summary: { backgroundColor: Theme.colors.primarySoft, borderRadius: 20, padding: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, label: { color: Theme.colors.muted, fontSize: 12 }, amount: { color: Theme.colors.text, fontSize: 20, fontWeight: '800', marginTop: 4 }, percent: { color: Theme.colors.primary, fontSize: 20, fontWeight: '800' }, section: { color: Theme.colors.text, fontSize: 16, fontWeight: '700' }, expense: { backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, expenseText: { flex: 1, gap: 4 }, name: { color: Theme.colors.text, fontSize: 14, fontWeight: '600' }, amountSmall: { color: Theme.colors.muted, fontSize: 12 }, status: { borderRadius: 100, paddingHorizontal: 10, paddingVertical: 5, fontSize: 11, fontWeight: '700' }, paid: { color: Theme.colors.success, backgroundColor: '#DFF6EE' }, unpaid: { color: '#966016', backgroundColor: '#FFF1DA' }, add: { minHeight: 52, backgroundColor: Theme.colors.primary, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, addText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' }, empty: { color: Theme.colors.muted, textAlign: 'center', padding: 30 } });
