import { useFocusEffect } from '@react-navigation/native';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Theme } from '@/constants/theme';
import { ChecklistItem, getChecklistItems, updateChecklistItem } from '@/data/checklists';

export default function EventChecklistScreen() {
  const { eventId } = useLocalSearchParams<{ eventId: string }>();
  const [items, setItems] = useState<ChecklistItem[]>(getChecklistItems(eventId));
  useFocusEffect(useCallback(() => { setItems(getChecklistItems(eventId)); }, [eventId]));
  const done = items.filter((item) => item.done).length;
  const grouped = useMemo(() => Array.from(new Set(items.map((item) => item.category))), [items]);
  const toggle = (id: string) => { const item = items.find((value) => value.id === id); if (item) { updateChecklistItem(id, { done: !item.done }); setItems(getChecklistItems(eventId)); } };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ กลับไปภาพรวม</Text></Pressable><View style={styles.headingRow}><View><Text style={styles.title}>เช็คลิสต์งาน</Text><Text style={styles.subtitle}>ติดตามทุกขั้นตอนให้งานเป็นไปอย่างราบรื่น</Text></View><Pressable onPress={() => router.push({ pathname: '/event/budget', params: { eventId } })} style={styles.budgetLink}><Text style={styles.budgetLinkText}>งบประมาณ</Text></Pressable></View><View style={styles.summary}><Summary label="ทั้งหมด" value={items.length} /><Summary label="เสร็จแล้ว" value={done} color={Theme.colors.success} /><Summary label="ค้างอยู่" value={items.length - done} color={Theme.colors.primary} /></View>{grouped.map((category) => <View key={category} style={styles.group}><Text style={styles.category}>{category}</Text>{items.filter((item) => item.category === category).map((item) => <ChecklistRow key={item.id} item={item} onToggle={() => toggle(item.id)} onEdit={() => router.push({ pathname: '/event/checklist-edit', params: { id: item.id } })} />)}</View>)}</ScrollView><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/event/checklist-new', params: { eventId } })} style={styles.add}><Text style={styles.addText}>＋ เพิ่มรายการเช็คลิสต์</Text></Pressable></SafeAreaView>;
}
function Summary({ label, value, color = Theme.colors.text }: { label: string; value: number; color?: string }) { return <View style={styles.summaryItem}><Text style={[styles.summaryValue, { color }]}>{value}</Text><Text style={styles.summaryLabel}>{label}</Text></View>; }
function ChecklistRow({ item, onToggle, onEdit }: { item: ChecklistItem; onToggle: () => void; onEdit: () => void }) { return <View style={styles.row}><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: item.done }} onPress={onToggle} style={[styles.checkbox, item.done && styles.checked]}><Text style={styles.check}>{item.done ? '✓' : ''}</Text></Pressable><Pressable onPress={onEdit} style={styles.itemBody}><Text style={[styles.itemTitle, item.done && styles.done]}>{item.title}</Text><Text style={styles.itemMeta}>{item.dueDate}{item.budget ? ` · ฿${item.budget.toLocaleString()}` : ''}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="แก้ไขรายการ" onPress={onEdit} style={styles.edit}><Text>✎</Text></Pressable></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Theme.colors.background }, content: { padding: 20, paddingBottom: 96, gap: 16 }, back: { color: Theme.colors.primary, fontSize: 14, fontWeight: '600', minHeight: 36 }, headingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, title: { color: Theme.colors.text, fontSize: 24, fontWeight: '800' }, subtitle: { color: Theme.colors.muted, fontSize: 13, marginTop: 4 }, budgetLink: { minHeight: 40, paddingHorizontal: 12, borderRadius: 12, backgroundColor: Theme.colors.primarySoft, justifyContent: 'center' }, budgetLinkText: { color: Theme.colors.primary, fontSize: 12, fontWeight: '700' }, summary: { flexDirection: 'row', gap: 10 }, summaryItem: { flex: 1, backgroundColor: Theme.colors.surface, borderRadius: 16, padding: 14, gap: 4 }, summaryValue: { fontSize: 22, fontWeight: '800' }, summaryLabel: { color: Theme.colors.muted, fontSize: 11 }, group: { gap: 8 }, category: { color: Theme.colors.text, fontSize: 15, fontWeight: '700', marginTop: 4 }, row: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 12, backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 14 }, checkbox: { width: 24, height: 24, borderWidth: 1.5, borderColor: Theme.colors.primary, borderRadius: 7, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: Theme.colors.primary }, check: { color: '#FFFFFF', fontWeight: '800' }, itemBody: { flex: 1, gap: 3 }, itemTitle: { color: Theme.colors.text, fontSize: 13 }, itemMeta: { color: Theme.colors.muted, fontSize: 11 }, done: { color: Theme.colors.muted, textDecorationLine: 'line-through' }, edit: { minWidth: 36, minHeight: 36, alignItems: 'center', justifyContent: 'center' }, add: { position: 'absolute', left: 20, right: 20, bottom: 20, minHeight: 52, borderRadius: 18, backgroundColor: Theme.colors.primary, alignItems: 'center', justifyContent: 'center' }, addText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' } });
