import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppText as Text } from '@/components/AppText';
import { AppButton } from '@/components/AppButton';
import { AppInput } from '@/components/AppInput';
import { Theme } from '@/constants/theme';
import { addChecklistItem, ChecklistCategory } from '@/data/checklists';
import { addEvent } from '@/data/events';

type Template = { id: string; title: string; category: ChecklistCategory; dueDate: string };
const eventTypes = ['งานแต่งงาน', 'งานสัมมนา', 'วันเกิด', 'งานเปิดตัว'];
const iconForType: Record<string, string> = { งานแต่งงาน: '💍', งานสัมมนา: '💼', วันเกิด: '🎈', งานเปิดตัว: '🎉' };
const templatesByType: Record<string, Template[]> = {
  งานแต่งงาน: [{ id: 'wedding-venue', title: 'เลือกสถานที่จัดงาน', category: 'สถานที่', dueDate: 'วางแผนต่อไป' }, { id: 'wedding-food', title: 'เลือกเมนูอาหารและเครื่องดื่ม', category: 'อาหาร', dueDate: 'วางแผนต่อไป' }, { id: 'wedding-decor', title: 'สรุปแบบตกแต่งสถานที่', category: 'ตกแต่ง', dueDate: 'วางแผนต่อไป' }],
  งานสัมมนา: [{ id: 'seminar-venue', title: 'จองห้องประชุม', category: 'สถานที่', dueDate: 'วางแผนต่อไป' }, { id: 'seminar-food', title: 'จัดเตรียมอาหารว่าง', category: 'อาหาร', dueDate: 'วางแผนต่อไป' }, { id: 'seminar-materials', title: 'เตรียมเอกสารและอุปกรณ์', category: 'อื่น ๆ', dueDate: 'วางแผนต่อไป' }],
  วันเกิด: [{ id: 'birthday-venue', title: 'เลือกสถานที่จัดปาร์ตี้', category: 'สถานที่', dueDate: 'วางแผนต่อไป' }, { id: 'birthday-food', title: 'สั่งอาหารและเค้ก', category: 'อาหาร', dueDate: 'วางแผนต่อไป' }, { id: 'birthday-decor', title: 'เตรียมของตกแต่ง', category: 'ตกแต่ง', dueDate: 'วางแผนต่อไป' }],
  งานเปิดตัว: [{ id: 'launch-venue', title: 'ยืนยันสถานที่เปิดตัว', category: 'สถานที่', dueDate: 'วางแผนต่อไป' }, { id: 'launch-materials', title: 'เตรียมสื่อประชาสัมพันธ์', category: 'อื่น ๆ', dueDate: 'วางแผนต่อไป' }, { id: 'launch-decor', title: 'จัดเตรียมเวทีและตกแต่ง', category: 'ตกแต่ง', dueDate: 'วางแผนต่อไป' }],
};

export default function NewEventScreen() {
  const [title, setTitle] = useState(''); const [type, setType] = useState(eventTypes[0]); const [date, setDate] = useState(''); const [budget, setBudget] = useState('');
  const templates = useMemo(() => templatesByType[type], [type]);
  const [selected, setSelected] = useState<string[]>(templates.map((item) => item.id));
  const chooseType = (value: string) => { setType(value); setSelected(templatesByType[value].map((item) => item.id)); };
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const submit = () => { const parsedBudget = Number(budget.replace(/[^0-9]/g, '')); if (!title.trim() || !date.trim() || !parsedBudget || parsedBudget <= 0) return Alert.alert('ข้อมูลไม่ครบ', 'กรุณากรอกชื่องาน วันที่ และงบประมาณเป็นตัวเลขบวก'); const event = addEvent({ title: title.trim(), date: date.trim(), venue: 'ยังไม่ได้ระบุสถานที่', kind: type, icon: iconForType[type], daysLeft: 0, progress: 0, status: 'upcoming', banner: '#FDE3EA', accent: Theme.colors.primary, budget: parsedBudget, guests: 0, pending: 0 }); templates.filter((item) => selected.includes(item.id)).forEach((item) => addChecklistItem({ eventId: event.id, title: item.title, category: item.category, dueDate: item.dueDate, budget: 0, note: '', done: false })); router.replace({ pathname: '/event/[id]', params: { id: event.id } }); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Text style={styles.title}>สร้างงาน</Text><Pressable onPress={() => router.back()}><Text style={styles.cancel}>ยกเลิก</Text></Pressable></View><View style={styles.tip}><Text style={styles.tipIcon}>💡</Text><View style={styles.tipText}><Text style={styles.tipTitle}>เคล็ดลับแนะนำสำหรับงานประเภทนี้</Text><Text style={styles.tipBody}>เมื่อเลือกประเภทงาน ระบบจะแนะนำเช็คลิสต์เบื้องต้นให้เลือก</Text></View></View><AppInput label="ชื่องาน" value={title} onChangeText={setTitle} placeholder="กรอกชื่องาน" /><Text style={styles.label}>ประเภทงาน</Text><View style={styles.types}>{eventTypes.map((item) => <Pressable key={item} onPress={() => chooseType(item)} style={[styles.type, item === type && styles.typeActive]}><Text style={[styles.typeText, item === type && styles.typeTextActive]}>{item}</Text></Pressable>)}</View><AppInput label="วันที่จัดงาน" value={date} onChangeText={setDate} placeholder="เช่น 14 ก.พ. 2569" /><AppInput label="งบประมาณ (บาท)" value={budget} onChangeText={setBudget} keyboardType="number-pad" placeholder="เช่น 150000" /><View style={styles.checklistHeader}><Text style={styles.label}>เช็คลิสต์เบื้องต้น</Text><Text style={styles.selected}>{selected.length}/{templates.length} รายการ</Text></View><View style={styles.checklist}>{templates.map((item) => <Pressable key={item.id} onPress={() => toggle(item.id)} style={styles.checkItem}><Text style={[styles.checkbox, selected.includes(item.id) && styles.checkboxActive]}>{selected.includes(item.id) ? '✓' : ''}</Text><View style={styles.checkText}><Text style={styles.checkTitle}>{item.title}</Text><Text style={styles.checkMeta}>{item.category} · {item.dueDate}</Text></View></Pressable>)}</View><AppButton title="สร้างงาน" onPress={submit} /><AppButton title="ยกเลิก" onPress={() => router.back()} variant="outline" /></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Theme.colors.background }, content: { padding: 24, paddingBottom: 40, gap: 14 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minHeight: 42 }, title: { color: Theme.colors.text, fontSize: 26, fontWeight: '800' }, cancel: { color: Theme.colors.primary, fontSize: 14, fontWeight: '700' }, tip: { flexDirection: 'row', gap: 12, padding: 16, backgroundColor: '#FDE3EA', borderWidth: 1, borderColor: Theme.colors.primary, borderRadius: 20 }, tipIcon: { fontSize: 22 }, tipText: { flex: 1, gap: 4 }, tipTitle: { color: Theme.colors.primary, fontSize: 14, fontWeight: '700' }, tipBody: { color: Theme.colors.text, fontSize: 12, lineHeight: 18 }, label: { color: Theme.colors.muted, fontSize: 13, fontWeight: '600' }, types: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, type: { borderWidth: 1, borderColor: Theme.colors.border, backgroundColor: Theme.colors.surface, borderRadius: 100, paddingHorizontal: 14, paddingVertical: 9 }, typeActive: { backgroundColor: Theme.colors.primary, borderColor: Theme.colors.primary }, typeText: { color: Theme.colors.muted, fontSize: 13 }, typeTextActive: { color: '#FFFFFF', fontWeight: '700' }, checklistHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 }, selected: { color: Theme.colors.primary, fontSize: 12, fontWeight: '700' }, checklist: { backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 18, padding: 12, gap: 10 }, checkItem: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 44 }, checkbox: { width: 22, height: 22, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 6, textAlign: 'center', color: '#FFFFFF', backgroundColor: Theme.colors.surface }, checkboxActive: { backgroundColor: Theme.colors.primary, borderColor: Theme.colors.primary }, checkText: { flex: 1, gap: 2 }, checkTitle: { color: Theme.colors.text, fontSize: 14, fontWeight: '600' }, checkMeta: { color: Theme.colors.muted, fontSize: 11 } });
