import { router } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Theme } from '@/constants/theme';
import { BUDGET_LIMIT, Expense, getExpenses, updateExpense } from '@/data/budget';

const money = (value: number) => `฿${value.toLocaleString('en-US')}`;
export default function BudgetScreen() {
  const [expenses, setExpenses] = useState<Expense[]>(getExpenses());
  const [editing, setEditing] = useState<string | null>(null);
  const total = useMemo(() => expenses.reduce((sum, item) => sum + item.amount, 0), [expenses]);
  const paid = useMemo(() => expenses.filter((item) => item.paid).reduce((sum, item) => sum + item.amount, 0), [expenses]);
  const categories = useMemo(() => Array.from(new Set(expenses.map((item) => item.category))).map((category) => ({ category, total: expenses.filter((item) => item.category === category).reduce((sum, item) => sum + item.amount, 0) })), [expenses]);
  useFocusEffect(useCallback(() => { setExpenses(getExpenses()); }, []));
  const togglePaid = (id: string) => { const item = expenses.find((expense) => expense.id === id); if (item) { updateExpense(id, { paid: !item.paid }); setExpenses(getExpenses()); } };
  const updateAmount = (id: string, value: string) => { updateExpense(id, { amount: Number(value.replace(/[^0-9]/g, '')) || 0 }); setExpenses(getExpenses()); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>งบประมาณรวม</Text><View style={styles.highlight}><Text style={styles.highlightLabel}>ใช้ไปแล้วทั้งหมด</Text><View style={styles.amountRow}><Text style={styles.amount}>{money(total)}</Text><Text style={styles.limit}> / {money(BUDGET_LIMIT)}</Text></View><View style={styles.bigTrack}><View style={[styles.bigProgress, { width: `${Math.min((total / BUDGET_LIMIT) * 100, 100)}%` }]} /></View><Text style={styles.usage}>{Math.round((total / BUDGET_LIMIT) * 100)}% ของงบประมาณ</Text></View><Text style={styles.sectionTitle}>📊 แยกตามหมวดค่าใช้จ่าย</Text><View style={styles.categoryList}>{categories.map((item) => <View key={item.category} style={styles.categoryCard}><View style={styles.rowBetween}><Text style={styles.categoryName}>{item.category}</Text><Text style={styles.categoryAmount}>{money(item.total)}</Text></View><View style={styles.track}><View style={[styles.progress, { width: `${Math.min((item.total / BUDGET_LIMIT) * 100, 100)}%` }]} /></View></View>)}</View><View style={styles.rowBetween}><Text style={styles.sectionTitle}>รายการค่าใช้จ่าย</Text><Pressable onPress={() => router.push('/budget/new')} style={styles.addButton}><Text style={styles.addText}>＋ เพิ่มค่าใช้จ่าย</Text></Pressable></View><View style={styles.expenseList}>{expenses.map((item) => <View key={item.id} style={styles.expenseCard}><View style={styles.rowBetween}><View style={{ flex: 1 }}><Text style={styles.expenseName}>{item.name}</Text><Text style={styles.categoryName}>{item.category}</Text></View>{editing === item.id ? <TextInput autoFocus keyboardType="number-pad" value={String(item.amount)} onChangeText={(value) => updateAmount(item.id, value)} onBlur={() => setEditing(null)} style={styles.editInput} /> : <Pressable onPress={() => setEditing(item.id)}><Text style={styles.expenseAmount}>{money(item.amount)}</Text></Pressable>}</View><View style={styles.rowBetween}><Text style={[styles.status, item.paid ? styles.paid : styles.unpaid]}>{item.paid ? '✓ จ่ายแล้ว' : 'ยังไม่จ่าย'}</Text><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: item.paid }} onPress={() => togglePaid(item.id)}><Text style={styles.editText}>{item.paid ? 'ทำเครื่องหมายว่ายังไม่จ่าย' : 'ทำเครื่องหมายว่าจ่ายแล้ว'}</Text></Pressable></View></View>)}</View><View style={styles.summary}><Text style={styles.summaryText}>จ่ายแล้ว {money(paid)}</Text><Text style={styles.summaryText}>คงเหลือ {money(BUDGET_LIMIT - total)}</Text></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Theme.colors.background }, content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 112, gap: 16 }, title: { color: Theme.colors.text, fontSize: 24, fontWeight: '800' }, highlight: { backgroundColor: Theme.colors.primarySoft, borderWidth: 1, borderColor: Theme.colors.primary, borderRadius: 22, padding: 20, gap: 12 }, highlightLabel: { color: Theme.colors.primary, textAlign: 'center', fontSize: 14, fontWeight: '700' }, amountRow: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center' }, amount: { color: Theme.colors.text, fontSize: 28, fontWeight: '800' }, limit: { color: Theme.colors.muted, fontSize: 14 }, bigTrack: { height: 8, backgroundColor: '#FFFFFF', borderRadius: 100, overflow: 'hidden' }, bigProgress: { height: '100%', backgroundColor: Theme.colors.primary }, usage: { color: Theme.colors.muted, fontSize: 12, textAlign: 'center' }, sectionTitle: { color: Theme.colors.text, fontSize: 16, fontWeight: '700' }, categoryList: { gap: 12 }, categoryCard: { backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 20, padding: 16, gap: 8 }, rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, categoryName: { color: Theme.colors.muted, fontSize: 12 }, categoryAmount: { color: Theme.colors.muted, fontSize: 12 }, track: { height: 6, backgroundColor: Theme.colors.border, borderRadius: 100, overflow: 'hidden' }, progress: { height: '100%', backgroundColor: Theme.colors.primary }, addButton: { minHeight: 40, paddingHorizontal: 12, borderRadius: 14, backgroundColor: Theme.colors.primarySoft, justifyContent: 'center' }, addText: { color: Theme.colors.primary, fontSize: 12, fontWeight: '700' }, expenseList: { gap: 10 }, expenseCard: { backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: 16, padding: 14, gap: 12 }, expenseName: { color: Theme.colors.text, fontSize: 14, fontWeight: '600' }, expenseAmount: { color: Theme.colors.text, fontSize: 14, fontWeight: '700' }, status: { fontSize: 12, fontWeight: '600' }, paid: { color: Theme.colors.success }, unpaid: { color: Theme.colors.primary }, editText: { color: Theme.colors.muted, fontSize: 11 }, editInput: { minWidth: 100, borderBottomWidth: 1, borderBottomColor: Theme.colors.primary, color: Theme.colors.text, fontSize: 14, textAlign: 'right' }, summary: { flexDirection: 'row', justifyContent: 'space-between', padding: 16, borderRadius: 16, backgroundColor: Theme.colors.text }, summaryText: { color: '#FFFFFF', fontSize: 13, fontWeight: '600' } });
