import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Theme } from '@/constants/theme';
import { events, EventItem } from '@/data/events';

type Filter = 'all' | 'upcoming' | 'completed';
export default function EventsScreen() {
  const [filter, setFilter] = useState<Filter>('all');
  const filtered = useMemo(() => filter === 'all' ? events : events.filter((event) => event.status === filter), [filter]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>งานของฉัน</Text><View style={styles.filters}><FilterButton label="ทั้งหมด" active={filter === 'all'} onPress={() => setFilter('all')} /><FilterButton label="กำลังจะถึง" active={filter === 'upcoming'} onPress={() => setFilter('upcoming')} /><FilterButton label="เสร็จแล้ว" active={filter === 'completed'} onPress={() => setFilter('completed')} /></View><View style={styles.list}>{filtered.map((event) => <EventCard key={event.id} event={event} onPress={() => router.push({ pathname: '/event/[id]', params: { id: event.id } })} />)}</View></ScrollView><Pressable accessibilityRole="button" accessibilityLabel="สร้างงานใหม่" onPress={() => router.push('/event/new')} style={styles.fab}><Text style={styles.fabText}>＋</Text></Pressable></SafeAreaView>;
}
function FilterButton({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.filter, active ? styles.filterActive : styles.filterInactive]}><Text style={[styles.filterText, active ? styles.activeText : styles.inactiveText]}>{label}</Text></Pressable>; }
function EventCard({ event, onPress }: { event: EventItem; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={[styles.banner, { backgroundColor: event.banner }]}><View style={styles.bannerInfo}><Text style={styles.icon}>{event.icon}</Text><Text style={[styles.days, { color: event.accent }]}>{event.status === 'completed' ? 'เสร็จแล้ว' : `อีก ${event.daysLeft} วัน`}</Text></View><View style={styles.kind}><Text style={[styles.kindText, { color: event.accent }]}>{event.kind}</Text></View></View><View style={styles.cardBody}><Text style={styles.eventTitle}>{event.title}</Text><Text style={styles.eventMeta}>{event.date} · {event.venue}</Text><View style={styles.progressRow}><View style={styles.track}><View style={[styles.progress, { width: `${event.progress}%`, backgroundColor: event.accent }]} /></View><Text style={styles.percent}>{event.progress}%</Text></View></View></Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Theme.colors.background }, content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 112, gap: 16 }, title: { color: Theme.colors.text, fontSize: 24, fontWeight: '800' }, filters: { flexDirection: 'row', gap: 8 }, filter: { minHeight: 40, paddingHorizontal: 16, borderRadius: Theme.radius.pill, alignItems: 'center', justifyContent: 'center' }, filterActive: { backgroundColor: Theme.colors.text }, filterInactive: { backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border }, filterText: { fontSize: 13, fontWeight: '600' }, activeText: { color: '#FFFFFF' }, inactiveText: { color: Theme.colors.muted }, list: { gap: 12 }, card: { backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.xl, overflow: 'hidden', elevation: 1 }, banner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 14 }, bannerInfo: { flexDirection: 'row', alignItems: 'center', gap: 8 }, icon: { fontSize: 22 }, days: { fontSize: 12, fontWeight: '600' }, kind: { backgroundColor: '#FFFFFF', paddingHorizontal: 10, paddingVertical: 4, borderRadius: Theme.radius.pill }, kindText: { fontSize: 11, fontWeight: '600' }, cardBody: { padding: 16, gap: 10 }, eventTitle: { color: Theme.colors.text, fontSize: 16, fontWeight: '800' }, eventMeta: { color: Theme.colors.muted, fontSize: 12 }, progressRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, track: { flex: 1, height: 6, backgroundColor: Theme.colors.border, borderRadius: Theme.radius.pill, overflow: 'hidden' }, progress: { height: '100%', borderRadius: Theme.radius.pill }, percent: { color: Theme.colors.muted, fontSize: 11, width: 28 }, fab: { position: 'absolute', right: 22, bottom: 96, width: 58, height: 58, borderRadius: 29, backgroundColor: Theme.colors.primary, alignItems: 'center', justifyContent: 'center', elevation: 5 }, fabText: { color: '#FFFFFF', fontSize: 28 }, pressed: { opacity: 0.82 } });
