import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ProductCard } from '@/components/ProductCard';
import { products } from '@/data/products';
import { Theme } from '@/constants/theme';

export default function HomeScreen() {
  const [cartCount, setCartCount] = useState(0);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.greeting}><View><Text style={styles.title}>สวัสดี คุณมิว 👋</Text><Text style={styles.subtitle}>วางแผนอีเวนต์ของคุณได้ง่ายขึ้น</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>มิว</Text></View></View><View style={styles.metrics}><Metric value="4" label="งานทั้งหมด" color={Theme.colors.primary} /><Metric value="3" label="กำลังจะถึง" color={Theme.colors.success} /><Metric value="฿310k" label="งบประมาณรวม" color={Theme.colors.text} /></View><View style={styles.tip}><Text style={styles.tipEmoji}>💡</Text><View style={styles.tipText}><Text style={styles.tipTitle}>เคล็ดลับวันนี้</Text><Text style={styles.tipBody}>จัดลำดับความสำคัญของงาน เพื่อให้อีเวนต์เป็นไปอย่างราบรื่น</Text></View></View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>บริการสำหรับอีเวนต์</Text><Text style={styles.seeAll}>ดูทั้งหมด →</Text></View><View style={styles.grid}>{products.map((product) => <ProductCard key={product.id} product={product} onPress={() => setCartCount((count) => count + 1)} />)}</View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>งานที่ใกล้กำหนด</Text><Text style={styles.seeAll}>ดูทั้งหมด →</Text></View><Task emoji="✅" title="จองสถานที่จัดงาน" detail="งานแต่งงาน · กำหนดพรุ่งนี้" /><Task emoji="🛠️" title="ตรวจสอบงบประมาณ" detail="งานเลี้ยงบริษัท · เลยกำหนด" /></ScrollView><Pressable accessibilityRole="button" accessibilityLabel="สร้างงานใหม่" onPress={() => router.push('/event/new')} style={styles.fab}><Text style={styles.fabText}>＋</Text>{cartCount > 0 ? <View style={styles.badge}><Text style={styles.badgeText}>{cartCount}</Text></View> : null}</Pressable></SafeAreaView>;
}
function Metric({ value, label, color }: { value: string; label: string; color: string }) { return <View style={styles.metric}><Text style={[styles.metricValue, { color }]}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Task({ emoji, title, detail }: { emoji: string; title: string; detail: string }) { return <View style={styles.task}><Text style={styles.taskEmoji}>{emoji}</Text><View><Text style={styles.taskTitle}>{title}</Text><Text style={styles.taskDetail}>{detail}</Text></View></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Theme.colors.background }, content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 112, gap: 16 }, greeting: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: Theme.colors.text, fontSize: 24, fontWeight: '800' }, subtitle: { color: Theme.colors.muted, fontSize: 14, marginTop: 4 }, avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: Theme.colors.primary, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#FFFFFF', fontWeight: '700' }, metrics: { flexDirection: 'row', gap: 10 }, metric: { backgroundColor: Theme.colors.surface, borderRadius: Theme.radius.lg, padding: 12, flex: 1, gap: 6 }, metricValue: { fontSize: 20, fontWeight: '800' }, metricLabel: { color: Theme.colors.muted, fontSize: 11 }, tip: { flexDirection: 'row', gap: 12, padding: 16, backgroundColor: Theme.colors.primarySoft, borderWidth: 1, borderColor: Theme.colors.primary, borderRadius: Theme.radius.xl }, tipEmoji: { fontSize: 24 }, tipText: { flex: 1, gap: 4 }, tipTitle: { color: Theme.colors.primary, fontSize: 14, fontWeight: '700' }, tipBody: { color: Theme.colors.text, fontSize: 12, lineHeight: 18 }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 4 }, sectionTitle: { color: Theme.colors.text, fontSize: 16, fontWeight: '700' }, seeAll: { color: Theme.colors.primary, fontSize: 12, fontWeight: '600' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, task: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: Theme.colors.surface, borderWidth: 1, borderColor: Theme.colors.border, padding: 14, borderRadius: 16 }, taskEmoji: { fontSize: 18 }, taskTitle: { color: Theme.colors.text, fontSize: 13, fontWeight: '600' }, taskDetail: { color: Theme.colors.muted, fontSize: 11, marginTop: 2 }, fab: { position: 'absolute', right: 22, bottom: 96, width: 58, height: 58, borderRadius: 29, backgroundColor: Theme.colors.primary, alignItems: 'center', justifyContent: 'center', elevation: 5 }, fabText: { color: '#FFFFFF', fontSize: 28, lineHeight: 30 }, badge: { position: 'absolute', right: -2, top: -2, minWidth: 20, height: 20, borderRadius: 10, backgroundColor: Theme.colors.warning, alignItems: 'center', justifyContent: 'center' }, badgeText: { color: Theme.colors.text, fontSize: 11, fontWeight: '700' } });
